kind: ConfigMap
apiVersion: v1
metadata:
  name: otel-collector
  namespace: default

data:
  relay: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
    exporters:
      otlp/jaeger:
        endpoint: "jaeger-collector.default.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:

        endpoint: "0.0.0.0:9000"
        namespace: default
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]
