jaeger:
  provisionDataStore:
    cassandra: false
    elasticsearch: false
    kafka: false
  allInOne:
    enabled: true
    service:
      headless: false
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false
